### PR TITLE
Update 05-community.Rmd

### PR DESCRIPTION
**Pull request by maelle**
I added some details to encourage contributions, hope it's fine 😉

### CODE REVIEW

**Review by sellorm — CHANGES_REQUESTED** [review]
Thanks for this Maëlle.

As much as I too would like to encourage further contributions to R Weekly, this feels overly long compared to the others. How do you feel about something like:

[R Weekly](https://rweekly.org/) is a community curated news site for R users with a weekly newsletter. Anyone can suggest new R content for the next issue, either [through the site](https://rweekly.org/submit), or via [GitHub](https://github.com/rweekly/rweekly.org/).

What do you think?

**Comment by maelle** [comment]
Perfect, thanks!

**Comment by sellorm** [comment]
Merged - thanks!

**Comment by maelle** [comment]
Thank *you* for the guide & being so reactive!

**Pull request merged**
